var Quote = "A person who never made a mistake never tried anything new.";
var Famous_person = "Albert Einstein";
var message = "".concat(Famous_person, " once said, ").concat(Quote);
console.log(message);
var Quote1 = "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.";
var Famous_person1 = "Bruce Lee";
var Quote2 = "workhard untill your account number looks like a cell phone number";
var Famous_person2 = "Muhammad Usama";
var message1 = "".concat(Famous_person1, " ").concat(Quote1);
var message2 = "".concat(Famous_person2, " said that, ").concat(Quote2);
console.log(message1);
console.log(message2);
