let Quote: String= "A person who never made a mistake never tried anything new.";
let Famous_person: String= "Albert Einstein";
let message= `${Famous_person} once said, ${Quote}`;
console.log(message);
let Quote1: String= "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.";
let Famous_person1: string= "Bruce Lee";
let Quote2: string= "workhard untill your account number looks like a cell phone number";
let Famous_person2: string="Muhammad Usama";
let message1= `${Famous_person1} ${Quote1}`;
let message2= `${Famous_person2} said that, ${Quote2}`;
console.log(message1);
console.log(message2);